language: cpp
dist: bionic

addons:
  apt:
    packages: &default_pkgs
      - libglib2.0-dev
      - python3-pip
      - python3-setuptools
      # - libstdc++6-4.9-dbg
      - ninja-build

matrix:
  include:
    - compiler: gcc
      env:
        - COMPILERC=gcc-7
        - COMPILERCXX=g++-7
      addons:
        apt:
          packages:
            - *default_pkgs
            - gcc-7
            - g++-7
    - compiler: clang
      env:
        - COMPILERC=clang-8
        - COMPILERCXX=clang++-8
      addons:
        apt:
          packages:
            - *default_pkgs
            - clang-8

install:
  # The meson included in the Xenial repositories is too old (0.29).
  - pip3 install meson
  # Hack to work around different versions of LLVM being installed and meson
  # always choosing the newest one, regardless of our specifications.
  - export CC=$COMPILERC
  - export CXX=$COMPILERCXX

script:
  - mkdir build
  - meson build
  - ninja -v -C build
  - meson test -v -C build
