language: cpp
dist: xenial

addons:
  apt:
    sources: &default_srcs
      - ubuntu-toolchain-r-test
    packages: &default_pkgs
      - libglib2.0-dev
      - python3-pip
      - python3-setuptools
      # - libstdc++6-4.9-dbg
      - llvm-4.0-dev
      - ninja-build

matrix:
  include:
    - compiler: gcc
      env:
        - COMPILERC=gcc-5
        - COMPILERCXX=g++-5
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - gcc-5
            - g++-5
    - compiler: gcc
      env:
        - COMPILERC=gcc-6
        - COMPILERCXX=g++-6
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - gcc-6
            - g++-6
    - compiler: gcc
      env:
        - COMPILERC=gcc-7
        - COMPILERCXX=g++-7
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - gcc-7
            - g++-7
    - compiler: clang
      env:
        - COMPILERC=clang-4.0
        - COMPILERCXX=clang++-4.0
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - clang-4.0
    - compiler: clang
      env:
        - COMPILERC=clang-5.0
        - COMPILERCXX=clang++-5.0
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - clang-5.0

install:
  # The meson included in the Xenial repositories is too old (0.29).
  - pip3 install meson
  # Hack to work around different versions of LLVM being installed and meson
  # always choosing the newest one, regardless of our specifications.
  - ln -s /usr/bin/llvm-config-4.0 $HOME/.local/bin/llvm-config
  - export CC=$COMPILERC
  - export CXX=$COMPILERCXX

script:
  - mkdir build
  - meson build
  - ninja -v -C build
  - meson test -v -C build
